DROP TABLE IF EXISTS `branch`;

CREATE TABLE IF NOT EXISTS `std6102041520165`.`branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `branch_no` VARCHAR(5) NOT NULL,
  `street` VARCHAR(150) NOT NULL,
  `city` VARCHAR(150) NOT NULL,
  `postcode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;