DROP TABLE IF EXISTS `client`;

CREATE TABLE IF NOT EXISTS `std6102041520165`.`client` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_no` VARCHAR(5) NULL DEFAULT NULL,
  `f_name` VARCHAR(100) NULL DEFAULT NULL,
  `l_name` VARCHAR(100) NULL DEFAULT NULL,
  `tel_no` VARCHAR(11) NULL DEFAULT NULL,
  `pref_type` VARCHAR(50) NULL DEFAULT NULL,
  `max_rent` FLOAT(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;